<script setup lang="ts">
import { IconEdit, IconPlus, IconSpeakerphone, IconTrash, IconX } from '@tabler/icons-vue'

definePageMeta({ layout: 'admin', middleware: 'admin' })
useSeoMeta({ title: '公告管理 | Zephyr Hub' })
interface Announcement { id: string; title: string; content: string; tone: 'info' | 'warning' | 'success'; status: 'draft' | 'published'; publishedAt: number | null; expiresAt: number | null; updatedAt: number }
const { data, refresh } = await useFetch<{ announcements: Announcement[] }>('/api/admin/announcements')
const toast = useAppToast()
const showForm = ref(false)
const editing = ref<Announcement | null>(null)
const deleting = ref<Announcement | null>(null)
const saving = ref(false)
const error = ref('')
const form = reactive({ title: '', content: '', tone: 'info' as Announcement['tone'], status: 'draft' as Announcement['status'], expiresAt: '' })
function dateTimeValue(value: number | null) { if (!value) return ''; const date = new Date(value - new Date(value).getTimezoneOffset() * 60000); return date.toISOString().slice(0, 16) }
function openCreate() { editing.value = null; Object.assign(form, { title: '', content: '', tone: 'info', status: 'draft', expiresAt: '' }); error.value = ''; showForm.value = true }
function openEdit(item: Announcement) { editing.value = item; Object.assign(form, { title: item.title, content: item.content, tone: item.tone, status: item.status, expiresAt: dateTimeValue(item.expiresAt) }); error.value = ''; showForm.value = true }
async function save() { saving.value = true; error.value = ''; try { await $fetch(editing.value ? `/api/admin/announcements/${editing.value.id}` : '/api/admin/announcements', { method: editing.value ? 'PATCH' : 'POST', body: { ...form, expiresAt: form.expiresAt ? new Date(form.expiresAt).toISOString() : null } }); await refresh(); showForm.value = false; toast.show(editing.value ? '公告已更新' : '公告已创建', 'success') } catch (value) { const failure = value as { data?: { message?: string }; message?: string }; error.value = failure.data?.message || failure.message || '保存公告失败' } finally { saving.value = false } }
async function remove() { if (!deleting.value) return; saving.value = true; try { await $fetch(`/api/admin/announcements/${deleting.value.id}`, { method: 'DELETE' }); deleting.value = null; await refresh(); toast.show('公告已删除', 'success') } finally { saving.value = false } }
const date = (value: number | null) => value ? new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }).format(value) : '不自动到期'
</script>

<template><div class="admin-page"><header class="admin-page__header"><div><span class="admin-kicker">ANNOUNCEMENTS</span><h1>公告管理</h1><p>发布后的公告会显示在所有普通用户的个人首页。</p></div><button class="button button--primary" @click="openCreate"><IconPlus :size="17" />新建公告</button></header><section class="announcement-list"><article v-for="item in data?.announcements || []" :key="item.id" class="admin-panel announcement-item" :data-tone="item.tone"><header><div><span>{{ item.status === 'published' ? '已发布' : '草稿' }}</span><h2>{{ item.title }}</h2></div><span class="status-label" :data-status="item.status === 'published' ? 'active' : 'disabled'">{{ item.status === 'published' ? '用户可见' : '仅管理员可见' }}</span></header><div><p>{{ item.content }}</p><small>到期：{{ date(item.expiresAt) }}</small></div><footer><button class="button button--quiet button--small" @click="openEdit(item)"><IconEdit :size="15" />编辑</button><button class="icon-button danger" title="删除公告" aria-label="删除公告" @click="deleting = item"><IconTrash :size="16" /></button></footer></article><div v-if="!data?.announcements.length" class="admin-empty admin-empty--large"><div><IconSpeakerphone :size="24" /><p>还没有公告</p><button class="button button--primary button--small" @click="openCreate">新建公告</button></div></div></section><div v-if="showForm" class="admin-modal-backdrop" @click.self="showForm = false"><section class="admin-modal" role="dialog" aria-modal="true"><header><div><span>ANNOUNCEMENT</span><h2>{{ editing ? '编辑公告' : '新建公告' }}</h2></div><button class="icon-button" title="关闭" aria-label="关闭" @click="showForm = false"><IconX :size="18" /></button></header><form class="admin-form" @submit.prevent="save"><label><span>标题</span><input v-model="form.title" required maxlength="160"></label><label><span>正文</span><textarea v-model="form.content" required rows="7" maxlength="5000" /></label><div class="form-grid"><label><span>类型</span><AppSelect v-model="form.tone"><option value="info">通知</option><option value="warning">提醒</option><option value="success">完成</option></AppSelect></label><label><span>状态</span><AppSelect v-model="form.status"><option value="draft">草稿</option><option value="published">发布</option></AppSelect></label></div><label><span>到期时间</span><input v-model="form.expiresAt" type="datetime-local"></label><p v-if="error" class="form-error">{{ error }}</p><footer><button type="button" class="button button--secondary" @click="showForm = false">取消</button><button class="button button--primary" :disabled="saving">{{ saving ? '保存中' : '保存公告' }}</button></footer></form></section></div><AppConfirmDialog :open="Boolean(deleting)" title="删除公告" :message="`删除后无法恢复。确定删除“${deleting?.title || ''}”？`" :busy="saving" @close="deleting = null" @confirm="remove" /></div></template>
